#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="/mnt/iusers01/fse-ugpgt01/eee01/t66389xz/MMSI-Project"
STUDY_ROOT="${PROJECT_ROOT}/playerprediction"

DATASET="${DATASET:-youtube}"
TASK="${TASK:-STI}"
WANDB_PROJECT="${WANDB_PROJECT:-mmsi-playerprediction}"
WANDB_ENTITY="${WANDB_ENTITY:-}"
VISUAL_FILM_LAYERS="${VISUAL_FILM_LAYERS:-3}"
FUSION_FILM_LAYERS="${FUSION_FILM_LAYERS:-1}"
FUSION_MODE="${FUSION_MODE:-standard}"
GRAPH_MODE="${GRAPH_MODE:-speaker_centered}"
CLASSIFIER_MODE="${CLASSIFIER_MODE:-standard}"
GRAPH_LAYERS="${GRAPH_LAYERS:-2}"
CENTER_LOSS_WEIGHT="${CENTER_LOSS_WEIGHT:-0.0}"
SUPCON_WEIGHT="${SUPCON_WEIGHT:-0.0}"
SEED="${SEED:-1234}"
JEPA_MASK_COUNT="${JEPA_MASK_COUNT:-1}"
JEPA_MOMENTUM="${JEPA_MOMENTUM:-0.99}"
JEPA_WEIGHT_OPTIONS="${JEPA_WEIGHT_OPTIONS:-0.0 0.05 0.1}"

cd "${STUDY_ROOT}"

for jepa_weight in ${JEPA_WEIGHT_OPTIONS}; do
  model_name="playerpred-${TASK,,}-${DATASET}-vf${VISUAL_FILM_LAYERS}-ff${FUSION_FILM_LAYERS}-${FUSION_MODE}-${GRAPH_MODE}-${CLASSIFIER_MODE}-gl${GRAPH_LAYERS}-seed${SEED}-j${jepa_weight}-jm${JEPA_MASK_COUNT}"
  echo "Submitting ${model_name}"
  sbatch \
    --job-name="${model_name}" \
    --export=ALL,DATASET="${DATASET}",TASK="${TASK}",USE_WANDB=1,WANDB_PROJECT="${WANDB_PROJECT}",WANDB_ENTITY="${WANDB_ENTITY}",VISUAL_FILM_LAYERS="${VISUAL_FILM_LAYERS}",FUSION_FILM_LAYERS="${FUSION_FILM_LAYERS}",FUSION_MODE="${FUSION_MODE}",GRAPH_MODE="${GRAPH_MODE}",CLASSIFIER_MODE="${CLASSIFIER_MODE}",GRAPH_LAYERS="${GRAPH_LAYERS}",CENTER_LOSS_WEIGHT="${CENTER_LOSS_WEIGHT}",SUPCON_WEIGHT="${SUPCON_WEIGHT}",SEED="${SEED}",JEPA_WEIGHT="${jepa_weight}",JEPA_MASK_COUNT="${JEPA_MASK_COUNT}",JEPA_MOMENTUM="${JEPA_MOMENTUM}",MODEL_NAME="${model_name}",WANDB_RUN_NAME="${model_name}" \
    run_ablation_sti.sbatch
done
